### ISSUE TITLE
Dashboard Spalte "Tame Animals" zeigt falsche Anzahl von Tieren

### ISSUE THREAD

**Issue by Schemfil** [pardeike/RimionshipServer#15]
**Describe the bug**
Die Dashboard Spalte "Tame Animals" zeigt nicht nur eigene gezähmte sondern auch "freundliche" Karawanen Tiere.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/86972764/189760120-fc6f9447-0f1e-48a1-ba6f-2aef6c711fe6.png)

**Comment by pardeike** [comment]
Eher für die Mod oder?
