### ISSUE TITLE
"Z.E." zeigen inaktive Spieler

### ISSUE THREAD

**Issue by Schemfil** [pardeike/RimionshipServer#33]
Beendet ein Spieler RimWorld (= keine Daten mehr) und es stand ein Event kurz bevor, wird dieses dauerhaft weiter in der Eventliste angezeigt und blockiert damit Platz für Events der aktiven Spieler.

Es könnte ein Timeout eingebaut werden, der nach 10 Minuten ohne erhaltene Daten alle Einträge dieses Spielers aus sämtlichen Highlight Tabellen entfernt um keine Daten-Leichen dort anzusammeln.

**Comment by pardeike** [comment]
fixed
